"""Teaching helpers for static energy-volume equation-of-state work."""

from __future__ import annotations

from pathlib import Path
from typing import Iterable, Sequence

import numpy as np
import pandas as pd
from scipy.constants import Avogadro, physical_constants


_HARTREE_J = physical_constants["Hartree energy"][0]
_HARTREE_TO_KJMOL = _HARTREE_J * Avogadro / 1000.0
_GPA_A3_TO_HA = 1.0e-21 / _HARTREE_J


def make_cubic_volume_series(
    a0_angstrom: float,
    volume_factors: Sequence[float] = (0.91, 0.94, 0.97, 1.00, 1.03, 1.06, 1.09),
) -> pd.DataFrame:
    """Return target cubic lattice parameters for selected V/V0 factors."""
    a0 = float(a0_angstrom)
    if a0 <= 0:
        raise ValueError("a0_angstrom must be positive.")

    factors = np.asarray(volume_factors, dtype=np.float64)
    if np.any(factors <= 0):
        raise ValueError("All volume factors must be positive.")

    v0 = a0**3
    a = a0 * np.cbrt(factors)
    v = v0 * factors

    return pd.DataFrame(
        {
            "V/V0": factors,
            "a/a0": np.cbrt(factors),
            "a target (Å)": a,
            "V target conventional (Å³)": v,
        }
    )


def write_file_list(
    outputs: Sequence[str | Path],
    destination: str | Path = "crystal-files.txt",
) -> Path:
    """Write one CRYSTAL output path per line for Quantas inpgen."""
    if not outputs:
        raise ValueError("No output files were supplied.")

    dest = Path(destination)
    dest.parent.mkdir(parents=True, exist_ok=True)
    text = "\n".join(str(Path(p)) for p in outputs) + "\n"
    dest.write_text(text, encoding="utf-8")
    return dest


def read_quantas_ev_dataset(path: str | Path) -> pd.DataFrame:
    """Read the plain-text E-V dataset generated by Quantas eos inpgen.

    The reader uses the FORMAT declaration as the authoritative column order.
    It intentionally ignores other metadata lines.
    """
    path = Path(path)
    lines = path.read_text(encoding="utf-8", errors="replace").splitlines()

    columns = None
    data_rows: list[list[float]] = []

    for raw in lines:
        line = raw.strip()
        if not line or line.startswith("#"):
            continue

        if line.upper().startswith("FORMAT "):
            columns = line.split()[1:]
            continue

        if columns is None:
            continue

        parts = line.split()
        if len(parts) != len(columns):
            continue

        try:
            values = [float(x.replace("D", "E").replace("d", "e")) for x in parts]
        except ValueError:
            continue
        data_rows.append(values)

    if columns is None:
        raise ValueError(f"{path}: no FORMAT declaration was found.")
    if not data_rows:
        raise ValueError(f"{path}: no numerical EOS rows were found.")

    return pd.DataFrame(data_rows, columns=columns)


def fit_bm3_with_quantas(path: str | Path):
    """Fit a BM3 Energy EOS using the public Quantas 2 API."""
    from quantas.api import eos

    dataset = eos.read_input(Path(path))
    request = eos.FitRequest(
        model="BM3",
        domain="ev",
        target="energy",
        options=eos.FitOptions(solver_options=eos.OLSOptions()),
        request_id="mineral-science-mgo-bm3",
    )
    result = eos.fit(dataset, request)

    if not result.fit.success:
        raise RuntimeError(result.fit.message)

    return result


def bm3_energy(
    volume_a3,
    *,
    e0_ha: float,
    v0_a3: float,
    k0_gpa: float,
    kp: float,
):
    """Evaluate the third-order Birch-Murnaghan integrated E(V) relation."""
    v = np.asarray(volume_a3, dtype=np.float64)
    x = (float(v0_a3) / v) ** (2.0 / 3.0)
    k0_ha_a3 = float(k0_gpa) * _GPA_A3_TO_HA

    return (
        float(e0_ha)
        + 9.0 * float(v0_a3) * k0_ha_a3 / 16.0
        * (
            (x - 1.0) ** 3 * float(kp)
            + (x - 1.0) ** 2 * (6.0 - 4.0 * x)
        )
    )


def bm3_pressure(
    volume_a3,
    *,
    v0_a3: float,
    k0_gpa: float,
    kp: float,
):
    """Evaluate the third-order Birch-Murnaghan pressure P(V) in GPa."""
    v = np.asarray(volume_a3, dtype=np.float64)
    eta = (float(v0_a3) / v) ** (1.0 / 3.0)

    return (
        1.5
        * float(k0_gpa)
        * (eta**7 - eta**5)
        * (1.0 + 0.75 * (float(kp) - 4.0) * (eta**2 - 1.0))
    )


def eos_teaching_table(
    dataset: pd.DataFrame,
    fit_result,
    *,
    formula_units_per_cell: int = 4,
) -> pd.DataFrame:
    """Build the student-facing table from a Quantas crystallographic E-V dataset."""
    if formula_units_per_cell < 1:
        raise ValueError("formula_units_per_cell must be positive.")

    required = {"V", "A", "E"}
    missing = required.difference(dataset.columns)
    if missing:
        raise ValueError(
            "Dataset is missing required columns: " + ", ".join(sorted(missing))
        )

    params = fit_result.parameter_values
    e0_sample = float(dataset.loc[dataset["E"].idxmin(), "E"])

    out = pd.DataFrame(
        {
            "a (Å)": dataset["A"].to_numpy(dtype=np.float64),
            "V (Å³)": dataset["V"].to_numpy(dtype=np.float64),
            "energy (Ha)": dataset["E"].to_numpy(dtype=np.float64),
        }
    )

    out["ΔE from sampled minimum (kJ mol⁻¹)"] = (
        (out["energy (Ha)"] - e0_sample)
        * _HARTREE_TO_KJMOL
        / formula_units_per_cell
    )
    out["pressure from BM3 (GPa)"] = bm3_pressure(
        out["V (Å³)"],
        v0_a3=params["V0"],
        k0_gpa=params["K0"],
        kp=params["KP"],
    )

    return out.sort_values("V (Å³)").reset_index(drop=True)


def plot_energy_volume(dataset: pd.DataFrame, fit_result):
    """Plot ab initio E(V) points and the Quantas BM3 fit."""
    import matplotlib.pyplot as plt

    params = fit_result.parameter_values
    volumes = dataset["V"].to_numpy(dtype=np.float64)

    grid = np.linspace(volumes.min(), volumes.max(), 300)
    curve = bm3_energy(
        grid,
        e0_ha=params["E0"],
        v0_a3=params["V0"],
        k0_gpa=params["K0"],
        kp=params["KP"],
    )

    fig, ax = plt.subplots()
    ax.scatter(dataset["V"], dataset["E"], label="CRYSTAL")
    ax.plot(grid, curve, label="BM3")
    ax.set_xlabel("Volume (Å³)")
    ax.set_ylabel("Energy (Ha)")
    ax.legend()
    fig.tight_layout()
    return fig, ax


def plot_pressure_volume(dataset: pd.DataFrame, fit_result):
    """Plot P(V) reconstructed from the fitted BM3 energy EOS."""
    import matplotlib.pyplot as plt

    params = fit_result.parameter_values
    volumes = dataset["V"].to_numpy(dtype=np.float64)
    grid = np.linspace(volumes.min(), volumes.max(), 300)

    pressure = bm3_pressure(
        grid,
        v0_a3=params["V0"],
        k0_gpa=params["K0"],
        kp=params["KP"],
    )

    fig, ax = plt.subplots()
    ax.plot(grid, pressure)
    ax.axhline(0.0, linewidth=0.8)
    ax.axvline(params["V0"], linewidth=0.8, linestyle="--")
    ax.set_xlabel("Volume (Å³)")
    ax.set_ylabel("Pressure (GPa)")
    fig.tight_layout()
    return fig, ax
